import numpy as np

matrixA = np.array([[1,2,3,],[4,5,6,],[7,8,9,]])

print()
print(f"matrixA:\n{matrixA}")
print("\nSomatorio de todos os dados")
print(f"{np.sum(matrixA) = }")
print("\nSomatorio das linhas")
print(f"{np.sum(matrixA, axis=0) = }")
print("\nSomatorio das colunas")
print(f"{np.sum(matrixA, axis=1) = }")
print()
print(f"{np.sum(matrixA) = }")
print("\nSomatorio das linhas mantendo o formato de linhas")
print(f"{np.sum(matrixA, axis=0, keepdims=True) = }")
print("\nSomatorio das colunas mantendo o formato de colunas")
print(f"{np.sum(matrixA, axis=1, keepdims=True) = }")
print()
print("\nValor maximo entre todos os dados")
print(f"{np.max(matrixA) = }")
print("\nValor maximo entre linhas")
print(f"{np.max(matrixA, axis=0) = }")
print("\nValor maximo entre colunas")
print(f"{np.max(matrixA, axis=1) = }")
